networks:
  shared-app:

services:
  ocserv_and_backend:
    restart: always
    image: ocserv_and_backend:ocserv
    container_name: ocserv_and_backend
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.Pack
    volumes:
      - ./volumes/ocserv:/etc/ocserv
      - ./volumes/db:/app/db
      - /etc/letsencrypt/live/oc15.sanctuaryimmersive.com:/etc/ocserv/certs
    ports:
      - 443:443/tcp
    # env_file:
    #   - ./prod.env
    networks:
      - shared-app

  nginx:
    restart: always
    image: nginx:ocserv
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.Front
    ports:
      - "8080:80"
    depends_on:
      - ocserv_and_backend
    # env_file:
    #   - ./prod.env
    networks:
      - shared-app
